### ISSUE TITLE
Cannot use different Wordpress versions

### ISSUE THREAD

**Issue by wonkeythemonkey** [Soluto/wordpress-plugin-tests-template#7] opened 2018-09-26 20:27 UTC
If you attempt to change the version of Wordpress in the `.env` file to anything other than `4.4`, the build stage will fail with the following error whenever `svn` is run:
```
Error relocating /usr/lib/libexpat.so.1: getrandom: symbol not found
```

I even tried adding a line to `install-wp-tests.sh` to run a simple `svn --version`, but the error message stopped the build right after that line.

**Comment by omerlh** [comment] 2018-10-02 16:36
Hey, thanks for reporting this issue :) I tried to find a solution today but didn't find any yet. I'll keep looking, but I have a lot on my plate right now so this might take a while.

**Comment by wonkeythemonkey** [comment] 2018-10-02 16:39
No problem! Is it a matter of knowing the cause of the problem but not having a solution, or not knowing the cause either?

If you know the cause, I might be able to fork it and hunt around a bit for a solution.

**Comment by omerlh** [comment] 2018-10-02 16:42
I have no clue. I was able to find some hints by googling things like `libexpat.so.1: getrandom: symbol not found` but couldn't find anything useful. I was able also to reproduce it on my machine. This issue libexpat/libexpat#50 seems to be related, and there is also this alpine issue sgerrand/alpine-pkg-glibc#13 but none of them helped me understand what the issue it.

**Comment by wonkeythemonkey** [comment] 2018-10-02 16:46
I found the same things when I googled it as well. It looks like a multilingual library isn't loading, but I can't imagine why changing a single value for a URL would change the libraries available to `svn`, of all things.

**Comment by omerlh** [comment] 2018-10-02 16:47
Yep, that what drives me crazy also. I wanted to try and run the SVN clone on a clean alpine box and see what happens, maybe it will reproduce - will try that when I have some time

**Comment by tannerhodges** [comment] 2021-02-18 14:21
Hey all, FWIW I've been able to update to WordPress 5.6 with the updates from #8 and build successfully.

```
PHP_IMAGE_TAG=7.0-alpine
WORDPRESS_VERSION=5.6
```

@omerlh Would it make sense to go ahead and bump the `.env` version?

If so, I can open another quick PR to (hopefully) resolve this issue.

**Comment by ebickle** [comment] 2023-08-28 16:24
We're archiving the repository but keeping it online in case it's helpful for others. As part of that we're closing the open issues and pull requests.

**Closed as completed by ebickle** 2023-08-28 16:24 UTC
